version : "3"
services:
    jenkins:
        image: jenkins/jenkins:lts
        environment:
            DOCKER_CERT_PATH: /certs/client
            DOCKER_HOST: tcp://docker:2376
        ports: 
            - 8080:8080
        volumes :
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
    docker:
        privileged: true
        image: docker:dind
        environment:
            DOCKER_TLS_CERTDIR: /certs
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client
        expose:
            - 2376
volumes:
    jenkins-data:
    jenkins-docker-certs: